FROM diffblue/cbmc-builder:alpine-0.0.1

LABEL maintainer="DiffBlue Ltd."

RUN apk add --no-cache openjdk8 jq maven apache-ant

ENV PATH="$PATH:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin" \
    JAVA_HOME="/usr/lib/jvm/java-1.8-openjdk"
